# Generated by Django 3.2.18 on 2023-03-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_content_imagepost_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='longitude',
        ),
    ]
