# Generated by Django 3.2.18 on 2023-03-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_imagepost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
